org.gradle.jvmargs=-Xmx1280m -XX:MaxMetaspaceSize=512m -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.daemon=true
kotlin.incremental=true
kotlin.daemon.jvmargs=-Xmx1024m
android.useAndroidX=true
android.enableJetifier=false
