// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSVoAxst038IvxwmZ8zrh-W4o-D_9JeOE',
    appId: '1:373212780191:web:48b473235a22e8ab70e51f',
    messagingSenderId: '373212780191',
    projectId: 'vishal-gold-app',
    authDomain: 'vishal-gold-app.firebaseapp.com',
    storageBucket: 'vishal-gold-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB5v9Aq7yPz6QRoLIBgPsvue5UcZgBQP0',
    appId: '1:373212780191:android:a7bdbcba05e8bc3c5874aa',
    messagingSenderId: '373212780191',
    projectId: 'vishal-gold-app',
    storageBucket: 'vishal-gold-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkWoV-D7atHBOiJP_EQ73lAkQh2EMxFnc',
    appId: '1:373212780191:ios:9fde0ed17951df6470e51f',
    messagingSenderId: '373212780191',
    projectId: 'vishal-gold-app',
    storageBucket: 'vishal-gold-app.firebasestorage.app',
    iosBundleId: 'com.example.vishalGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkWoV-D7atHBOiJP_EQ73lAkQh2EMxFnc',
    appId: '1:564443743822:ios:9fde0ed17951df6470e51f',
    messagingSenderId: '564443743822',
    projectId: 'vishal-gold',
    storageBucket: 'vishal-gold.firebasestorage.app',
    iosBundleId: 'com.example.vishalGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSVoAxst038IvxwmZ8zrh-W4o-D_9JeOE',
    appId: '1:564443743822:web:7e09e385c993147e70e51f',
    messagingSenderId: '564443743822',
    projectId: 'vishal-gold',
    authDomain: 'vishal-gold.firebaseapp.com',
    storageBucket: 'vishal-gold.firebasestorage.app',
  );
}
