// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI34SRMQ8Oa2zrqcXFQoMGwYZarYOkuNc',
    appId: '1:416576636573:web:48b473235a22e8ab70e51f', // Assuming web ID follows pattern or needs update
    messagingSenderId: '416576636573',
    projectId: 'vishal-jewelers',
    authDomain: 'vishal-jewelers.firebaseapp.com',
    storageBucket: 'vishal-jewelers.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI34SRMQ8Oa2zrqcXFQoMGwYZarYOkuNc',
    appId: '1:416576636573:android:726183fc873d94e63d7674',
    messagingSenderId: '416576636573',
    projectId: 'vishal-jewelers',
    storageBucket: 'vishal-jewelers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI34SRMQ8Oa2zrqcXFQoMGwYZarYOkuNc',
    appId: '1:416576636573:ios:9fde0ed17951df6470e51f', // Assuming iOS ID follows pattern
    messagingSenderId: '416576636573',
    projectId: 'vishal-jewelers',
    storageBucket: 'vishal-jewelers.firebasestorage.app',
    iosBundleId: 'com.vishaljewelersapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI34SRMQ8Oa2zrqcXFQoMGwYZarYOkuNc',
    appId: '1:416576636573:ios:9fde0ed17951df6470e51f',
    messagingSenderId: '416576636573',
    projectId: 'vishal-jewelers',
    storageBucket: 'vishal-jewelers.firebasestorage.app',
    iosBundleId: 'com.vishaljewelersapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI34SRMQ8Oa2zrqcXFQoMGwYZarYOkuNc',
    appId: '1:416576636573:web:7e09e385c993147e70e51f',
    messagingSenderId: '416576636573',
    projectId: 'vishal-jewelers',
    authDomain: 'vishal-jewelers.firebaseapp.com',
    storageBucket: 'vishal-jewelers.firebasestorage.app',
  );
}
